# __init__.py
# Copyright 2025 Roger Marsh
# Licence: See LICENCE (BSD licence)

"""Help files for ChessTagCQL.

The options in the Help menu are named in the DATA section below.  Each is
backed by an "rst" file, displayed by invoking the menu option, and a "html"
file generated by "rst2html".

The two file names which are not obvious when viewing the directory "help_"
are "keyboard", associated with ACTIONS, and "chesstab", associated with
NOTES.
"""

import os

ABOUT = "About"
FILESIZE = "FileSize"
GUIDE = "Guide"
NOTES = "Notes"
SELECTION = "Selection"

_textfile = {
    ABOUT: ("aboutchesstagcql",),
    FILESIZE: ("filesize",),
    GUIDE: ("guide",),
    NOTES: ("chesstagcql",),
    SELECTION: ("selection",),
}

folder = os.path.dirname(__file__)

for k in list(_textfile.keys()):
    _textfile[k] = tuple(
        os.path.join(folder, ".".join((n, "rst"))) for n in _textfile[k]
    )

del folder, k, os
